=== unshiv/Xml/src/main/resources/Student.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://www.example.org/Student" 
xmlns:tns="http://www.example.org/Student" 
elementFormDefault="qualified">

    <complexType name="Student">
    	<sequence>
    		<element name="name" type="string"></element>
    		<element name="number" type="int"></element>
    		<element name="address" type="tns:addressType" maxOccurs="1" minOccurs="1"></element>
    		<element name="marks" type="tns:marks" maxOccurs="1" minOccurs="1"></element>
    	</sequence>
    </complexType>


    <complexType name="addressType">
    	<sequence>
    		<element name="home" type="tns:Address" maxOccurs="1" minOccurs="1"></element>
    		<element name="communication" type="tns:Address" maxOccurs="1" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="marks">
    	<sequence>
    		<element name="subject" type="string"></element>
    		<element name="marks" type="float"></element>
    		<element name="maxMarks" type="float"></element>
    	</sequence>
    </complexType>


    <element name="Student" type="tns:Student"></element>


    <complexType name="Address">
    	<sequence>
    		<element name="streetName" type="string"></element>
    		<element name="city" type="string"></element>
    		<element name="state" type="string"></element>
    		<element name="zip" type="string"></element>
    	</sequence>
    </complexType>
</schema>

=== unshiv/Xml/src/main/resources/Student.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Student xmlns:tns="http://www.example.org/Student" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Student Student.xsd ">
  <tns:name>tns:name</tns:name>
  <tns:number>0</tns:number>
  <tns:address>
    <tns:HOME>
      <tns:streetName>tns:streetName</tns:streetName>
      <tns:city>tns:city</tns:city>
      <tns:state>tns:state</tns:state>
      <tns:zip>tns:zip</tns:zip>
    </tns:HOME>
    <tns:COMMUNICATION>
      <tns:streetName>tns:streetName</tns:streetName>
      <tns:city>tns:city</tns:city>
      <tns:state>tns:state</tns:state>
      <tns:zip>tns:zip</tns:zip>
    </tns:COMMUNICATION>
  </tns:address>
  <tns:marks>
    <tns:subject>tns:subject</tns:subject>
    <tns:marks>0.0</tns:marks>
    <tns:maxMarks>0.0</tns:maxMarks>
  </tns:marks>
</tns:Student>
